# Generated by Django 4.1.7 on 2024-08-12 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='학번')),
                ('email_vcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='이메일 인증번호')),
                ('phone_vcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='휴대전화 번호 인증번호')),
                ('confirmed', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('will_expire_on', models.DateTimeField(blank=True, null=True, verbose_name='만료 예정 일시')),
            ],
            options={
                'verbose_name': '인증번호',
                'verbose_name_plural': '인증번호들',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='학번')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='성명')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='휴대전화 번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 추가 정보',
                'verbose_name_plural': '사용자 추가 정보들',
            },
        ),
    ]
