# Generated by Django 4.1.7 on 2023-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="학번"
                    ),
                ),
                (
                    "email_vcode",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="이메일 인증번호"
                    ),
                ),
                (
                    "phone_vcode",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="휴대전화 번호 인증번호"
                    ),
                ),
                ("confirmed", models.BooleanField(default=False, verbose_name="인증 여부")),
                (
                    "will_expire_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="만료 예정 일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "인증번호",
                "verbose_name_plural": "인증번호(들)",
            },
        ),
    ]
