# Generated by Django 4.1.7 on 2024-01-13 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_vcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadata",
            options={"verbose_name": "사용자 추가 정보", "verbose_name_plural": "사용자 추가 정보들"},
        ),
        migrations.AlterModelOptions(
            name="vcode",
            options={"verbose_name": "인증번호", "verbose_name_plural": "인증번호들"},
        ),
    ]
