# Generated by Django 4.1.7 on 2024-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="학번"
                    ),
                ),
                (
                    "purpose_priority",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="목적"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="기간"
                    ),
                ),
                ("equipment", models.JSONField(verbose_name="기자재")),
            ],
            options={
                "verbose_name": "장바구니",
                "verbose_name_plural": "장바구니들",
            },
        ),
        migrations.DeleteModel(
            name="RentalApplication",
        ),
    ]
