# Generated by Django 4.1.7 on 2024-03-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="equipment",
            field=models.JSONField(blank=True, null=True, verbose_name="기자재"),
        ),
    ]
