# Generated by Django 4.1.7 on 2024-03-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0004_alter_cart_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="will_expire_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="만료 예정 일시"),
        ),
    ]
