# Generated by Django 4.1.7 on 2024-04-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0005_cart_will_expire_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="period",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="기간"
            ),
        ),
    ]
