# Generated by Django 4.1.7 on 2024-08-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_cart_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
