# Generated by Django 4.1.7 on 2024-01-13 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notice",
        ),
    ]
